load("@yacl//bazel:yacl.bzl", "AES_COPT_FLAGS")
load("//bazel:curve.bzl", "curve_cc_binary", "curve_cc_library", "curve_cc_test")

package(default_visibility = ["//visibility:public"])

curve_cc_library(
    name = "ecdh_psi",
    srcs = ["ecdh_psi.cc"],
    hdrs = ["ecdh_psi.h"],
    linkopts = select({
        "@platforms//os:windows": ["/FORCE:UNRESOLVED"],
        "@platforms//os:linux": ["-static-libstdc++", "-static-libgcc"],
        "//conditions:default": [],
    }),
    deps = [
        "@psi//psi/algorithm/ecdh:ecdh_psi",
        "@yacl//yacl/crypto/rand",
        "@yacl//yacl/link:context",
        "//cpp/tools/network:network_utils",
        "@com_github_nlohmann_json//:json",
    ],
)


curve_cc_binary(
    name = "ecdh_psi_test",
    srcs = ["ecdh_psi_test.cc"],
    deps = [
        ":ecdh_psi",
    ],
)

curve_cc_binary(
    name = "ecdh_psi_test_brpc",
    srcs = ["ecdh_psi_test_brpc.cc"],
    deps = [
        ":ecdh_psi",
    ],
)
