
image: $REGISTRY_URL/tensor_images/spu_tensor_amd64:v0.1.0


variables:
  APP_NAME: secure_protocol_lib

before_script:
  - mkdir -p ~/.pip
  - echo [global] > ~/.pip/pip.conf
  - echo index-url = https://mirrors.aliyun.com/pypi/simple/ >> ~/.pip/pip.conf
  - pip install devpi-client==5.0.0
  - devpi use $DEVPI_URL
  - devpi login $DEVPI_USERNAME --password=$DEVPI_PASSWORD
 
stages:
  - test
  - build

test:
  stage: test
  script:
    - echo mock make test
  only:
    - dev
    - master
    - /^release\/.*$/
    - tags
  tags:
    - k8s-ci

build-dev:
  stage: build
  script:
    - devpi use root/dev/+simple/
    - python setup.py sdist bdist_wheel
    - devpi upload --from-dir dist
    
  only:
    - dev
    - master
    - /^release\/.*$/

  tags:
    - k8s-ci

build-release:
  stage: build
  script:
    - devpi use root/release/+simple/
    - python setup.py sdist bdist_wheel
    - devpi upload --from-dir dist
  only:
    - tags
  tags:
    - k8s-ci

    
